#!/usr/bin/env bash

set -euo pipefail # Bash 'strict mode'
export TERM=xterm-256color

tput setaf 3 # set text colour
echo '
      (¯`·¯`·.¸¸.··´¯)
      ( \          / )
       ( ) Kirill ( )
        (/        \)
         (.·´¯`·.¸) '

tput setaf 36
echo ''
echo 'Installing backend dependencies.'
echo '================================'
tput sgr0 # reset text colour
cwd=$(pwd)
gem install rspec
cd server && bundle install
cd "$cwd"

tput setaf 36
echo ''
echo 'Running backend tests.'
echo '======================='
tput sgr0
cd server && bundle exec rspec
cd "$cwd"

tput setaf 36
echo ''
echo 'Installing frontend dependencies.'
echo '================================='
tput sgr0
npm i

tput setaf 36
echo ''
echo 'Running frontend tests.'
echo '======================='
tput sgr0
npm test

tput setaf 36
echo ''
echo 'Build frontend JavaScript bundle.'
echo '================================='
tput sgr0
cd server && npx parcel build --dist-dir lib/public/js lib/js/src/app.js
cd "$cwd"